/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.pets;

import java.awt.event.ActionListener;

/**
 *
 * @author fermigo
 */
public class PetsDialog extends javax.swing.JDialog {

    /**
     * Creates new form PetsDialog
     */
    public PetsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petsButton = new javax.swing.JButton();
        addCatButton = new javax.swing.JButton();
        addDogButton = new javax.swing.JButton();
        petsScrollPane = new javax.swing.JScrollPane();
        petsTextArea = new javax.swing.JTextArea();
        listPetsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        petsButton.setText("Pets");

        addCatButton.setText("Add cat");

        addDogButton.setText("Add dog");

        petsTextArea.setColumns(20);
        petsTextArea.setRows(5);
        petsScrollPane.setViewportView(petsTextArea);

        listPetsButton.setText("List pets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(petsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(petsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listPetsButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petsButton)
                    .addComponent(addCatButton)
                    .addComponent(addDogButton)
                    .addComponent(listPetsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(petsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addCatButtonActionListener(ActionListener listener) {
        this.addCatButton.addActionListener(listener);
    }

    public void addDogButtonActionListener(ActionListener listener) {
        this.addDogButton.addActionListener(listener);
    }

    public void addPetsButtonActionListener(ActionListener listener) {
        this.petsButton.addActionListener(listener);
    }

    public void addListPetsButtonActionListener(ActionListener listener) {
        this.listPetsButton.addActionListener(listener);
    }

    public void appendLine(String line) {
        this.petsTextArea.append(line + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCatButton;
    private javax.swing.JButton addDogButton;
    private javax.swing.JButton listPetsButton;
    private javax.swing.JButton petsButton;
    private javax.swing.JScrollPane petsScrollPane;
    private javax.swing.JTextArea petsTextArea;
    // End of variables declaration//GEN-END:variables
}
