/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.table;

import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fermigo
 */
public class TableDialog extends javax.swing.JDialog {

    /**
     * Creates new form TableDialog
     */
    public TableDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userTableScrollPane = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        addUserButton = new javax.swing.JButton();
        getInfoButton = new javax.swing.JButton();
        clearTableButton = new javax.swing.JButton();
        tableLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname"
            }
        ));
        userTableScrollPane.setViewportView(userTable);

        addUserButton.setText("Add user");

        getInfoButton.setText("Get info");

        clearTableButton.setText("Clear table");

        tableLabel.setText("Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(getInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clearTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tableLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton)
                    .addComponent(getInfoButton)
                    .addComponent(clearTableButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAddUserButtonActionListener(ActionListener listener) {
        this.addUserButton.addActionListener(listener);
    }

    public void addGetInfoButtonActionListener(ActionListener listener) {
        this.getInfoButton.addActionListener(listener);
    }

    public void addClearTableButtonActionListener(ActionListener listener) {
        this.clearTableButton.addActionListener(listener);
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.userTable.getModel();
        model.setRowCount(0);
        userTable.clearSelection();
        userTable.revalidate();
        userTable.repaint();
    }

    public void addTableModelListener(TableModelListener listener) {
        userTable.getModel().addTableModelListener(listener);
    }

    public void addRowTable(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.userTable.getModel();
        model.addRow(row);
    }

    public String getCellInfo() {
        String info = "";
        int row = this.userTable.getSelectedRow();
        int col = this.userTable.getSelectedColumn();
        if (col >= 0 && row >= 0) {
            info = this.userTable.getModel().getValueAt(row, col).toString();
        }
        return info;
    }

        public String getCellInfo(int row, int col) {
        String info = "";
        if (col >= 0 && row >= 0) {
            info = this.userTable.getModel().getValueAt(row, col).toString();
        }
        return info;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton clearTableButton;
    private javax.swing.JButton getInfoButton;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JTable userTable;
    private javax.swing.JScrollPane userTableScrollPane;
    // End of variables declaration//GEN-END:variables
}
