/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DAM2_Alu10
 */
public class ReserveJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReserveJFrame
     */
    public ReserveJFrame(MainJFrame view, boolean par) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        BannerjLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameTextField = new javax.swing.JTextField();
        namejLabel = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        surnamejLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailjLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        phonejLabel = new javax.swing.JLabel();
        EventDatajLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        PersonalDatajLabel1 = new javax.swing.JLabel();
        eventDateTextField1 = new javax.swing.JTextField();
        eventDatejLabel1 = new javax.swing.JLabel();
        eventTypejLabel1 = new javax.swing.JLabel();
        feastjRadioButton = new javax.swing.JRadioButton();
        congressjRadioButton = new javax.swing.JRadioButton();
        dayTripjRadioButton = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        kitchenjComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        roomsjLabel3 = new javax.swing.JLabel();
        roomsjCheckBox = new javax.swing.JCheckBox();
        sendjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BannerjLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        BannerjLabel.setText("Salón Palace Hotel ALD");

        nameTextField.setToolTipText("");
        nameTextField.setName(""); // NOI18N

        namejLabel.setText("Name:");

        surnameTextField.setToolTipText("");
        surnameTextField.setName(""); // NOI18N

        surnamejLabel.setText("Surname:");

        emailTextField.setToolTipText("");
        emailTextField.setName(""); // NOI18N

        emailjLabel.setText("Email:");

        phoneTextField.setToolTipText("");
        phoneTextField.setName(""); // NOI18N

        phonejLabel.setText("Phone Number:");

        EventDatajLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        EventDatajLabel.setText("Event Data");

        PersonalDatajLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        PersonalDatajLabel1.setText("Personal Data");

        eventDateTextField1.setToolTipText("");
        eventDateTextField1.setName(""); // NOI18N

        eventDatejLabel1.setText("Event Date(DD/MM/YYYY):");

        eventTypejLabel1.setText("Event Type:");

        buttonGroup1.add(feastjRadioButton);
        feastjRadioButton.setText("Feast");

        buttonGroup1.add(congressjRadioButton);
        congressjRadioButton.setText("Congress");

        buttonGroup1.add(dayTripjRadioButton);
        dayTripjRadioButton.setText("Day trip");

        jLabel1.setText("Nº of Attendants:");

        kitchenjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buffet", "Card", "Date with chef", "Without service" }));
        kitchenjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenjComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Kitchen:");

        roomsjLabel3.setText("Rooms for attendants?");

        buttonGroup2.add(roomsjCheckBox);
        roomsjCheckBox.setText("YES");

        sendjButton.setText("Send");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BannerjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namejLabel)
                            .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnamejLabel)
                            .addComponent(emailjLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonejLabel)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EventDatajLabel)
                    .addComponent(eventDatejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventTypejLabel1)
                    .addComponent(feastjRadioButton)
                    .addComponent(congressjRadioButton)
                    .addComponent(dayTripjRadioButton)
                    .addComponent(eventDateTextField1))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner1)
                        .addComponent(jLabel2))
                    .addComponent(kitchenjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomsjLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomsjCheckBox)
                    .addComponent(sendjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(PersonalDatajLabel1)
                    .addContainerGap(487, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BannerjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(354, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EventDatajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(surnamejLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eventDatejLabel1)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eventDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(emailjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phonejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eventTypejLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(feastjRadioButton)
                                    .addComponent(kitchenjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dayTripjRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(congressjRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(roomsjLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(roomsjCheckBox)))))
                        .addGap(8, 8, 8)
                        .addComponent(sendjButton)
                        .addGap(27, 27, 27))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(PersonalDatajLabel1)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitchenjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitchenjComboBoxActionPerformed

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BannerjLabel;
    private javax.swing.JLabel EventDatajLabel;
    private javax.swing.JLabel PersonalDatajLabel1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton congressjRadioButton;
    private javax.swing.JRadioButton dayTripjRadioButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField eventDateTextField1;
    private javax.swing.JLabel eventDatejLabel1;
    private javax.swing.JLabel eventTypejLabel1;
    private javax.swing.JRadioButton feastjRadioButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> kitchenjComboBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JCheckBox roomsjCheckBox;
    private javax.swing.JLabel roomsjLabel3;
    private javax.swing.JButton sendjButton;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JLabel surnamejLabel;
    // End of variables declaration//GEN-END:variables
}
