/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.aldComputers;

import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.JTextField;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lubián_Gañete_Julio_Miguel
 */
public class ManageAldComputersDialog extends javax.swing.JDialog {

    /**
     * Creates new form TableDialog
     */
    public ManageAldComputersDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userTableScrollPane = new javax.swing.JScrollPane();
        computerTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        tableLabel = new javax.swing.JLabel();
        computerEditorLabel = new javax.swing.JLabel();
        computerTypeLabel = new javax.swing.JLabel();
        computerSerialLabel = new javax.swing.JLabel();
        computerBrandLabel = new javax.swing.JLabel();
        computerModelLabel = new javax.swing.JLabel();
        serialTextField = new javax.swing.JTextField();
        brandTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        computerTypeComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addComputerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        computerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Brand", "Model"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        userTableScrollPane.setViewportView(computerTable);

        addButton.setText("Add Computer");

        editButton.setText("Edit Computer");

        deleteButton.setText("Delete computer");

        tableLabel.setText("ALD Computers");

        computerEditorLabel.setText("Computer Editor");

        computerTypeLabel.setText("Computer Type");

        computerSerialLabel.setText("Serial");

        computerBrandLabel.setText("Brand");

        computerModelLabel.setText("Model");

        serialTextField.setEnabled(false);
        serialTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialTextFieldActionPerformed(evt);
            }
        });

        brandTextField.setEnabled(false);

        modelTextField.setEnabled(false);

        computerTypeComboBox.setEnabled(false);

        saveButton.setText("Save");
        saveButton.setVisible(false);

        cancelButton.setText("Cancel");
        cancelButton.setVisible(false);

        addComputerButton.setText("Add");
        addComputerButton.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(computerEditorLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(computerTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerBrandLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerModelLabel)
                        .addGap(18, 18, 18)
                        .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerSerialLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addComputerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableLabel)
                    .addComponent(computerEditorLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(editButton)
                            .addComponent(deleteButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(computerTypeLabel)
                                    .addComponent(computerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addComputerButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(computerSerialLabel)
                                    .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(1, 1, 1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(computerBrandLabel)
                            .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(computerModelLabel)
                                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(cancelButton)
                                .addGap(41, 41, 41))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serialTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialTextFieldActionPerformed

    }//GEN-LAST:event_serialTextFieldActionPerformed

    public void addAddButtonActionListener(ActionListener listener) {
        this.addButton.addActionListener(listener);
    }

    public void addEditButtonActionListener(ActionListener listener) {
        this.editButton.addActionListener(listener);
    }

    public void addDeleteButtonActionListener(ActionListener listener) {
        this.deleteButton.addActionListener(listener);
    }

    public void addTableModelListener(TableModelListener listener) {
        computerTable.getModel().addTableModelListener(listener);
    }

    public void addComputersTableModel(TableModel tableModel) {
        computerTable.setModel(tableModel);
    }

    public TableModel getComputersTableModel() {
        return computerTable.getModel();
    }

    public String getCellInfo() {
        String info = "";
        int row = this.computerTable.getSelectedRow();
        int col = this.computerTable.getSelectedColumn();
        if (col >= 0 && row >= 0) {
            info = this.computerTable.getModel().getValueAt(row, col).toString();
        }
        return info;
    }

    public String getCellInfo(int row, int col) {
        String info = "";
        if (col >= 0 && row >= 0) {
            info = this.computerTable.getModel().getValueAt(row, col).toString();
        }
        return info;
    }

    public void addserialTextFieldActionListener(ActionListener listener) {
        this.serialTextField.addActionListener(listener);
    }

    public void setSerialTextField(String text) {
        serialTextField.setText(text);
    }

    public void setBrandTextField(String text) {
        brandTextField.setText(text);
    }

    public void setModelTextField(String text) {
        modelTextField.setText(text);
    }

    public javax.swing.JTable getComputerTable() {
        return computerTable;
    }

    public void enableTextFields(boolean b) {
        this.modelTextField.setEnabled(b);
        this.serialTextField.setEnabled(b);
        this.brandTextField.setEnabled(b);
    }
    
    public void addSaveButtonActionListener(ActionListener listener) {
        this.saveButton.addActionListener(listener);
    }
    
    public void modifyTableRow(int rowIndex, String serial, String brand, String modelValue) {
        DefaultTableModel tableModel = (DefaultTableModel) computerTable.getModel();
        tableModel.setValueAt(serial, rowIndex, 0);
        tableModel.setValueAt(brand, rowIndex, 1);
        tableModel.setValueAt(modelValue, rowIndex, 2);
    }
    
    public JTextField getSerialTextField() {
        return serialTextField;
    }
    
    public JTextField getBrandTextField() {
        return brandTextField;
    }

    public JTextField getModelTextField() {
        return modelTextField;
    }
    
    public void addCancelButtonActionListener(ActionListener listener) {
        this.cancelButton.addActionListener(listener);
    }
    
    public void changeComboBoxModel(ComboBoxModel cmbm){
        this.computerTypeComboBox.setModel(cmbm);
    }
    
    public void selectInComboBox(int indice){
        computerTypeComboBox.setSelectedIndex(indice);
    }
    
    public void addAddComputerButtonActionListener(ActionListener listener) {
        this.addComputerButton.addActionListener(listener);
    }
    
    public void setVisibleAddComputerButton(Boolean b){
        this.addComputerButton.setVisible(b);
    }
    
    public void setVisibleCancelComputerButton(Boolean b){
        this.cancelButton.setVisible(b);
    }
    
    public void setVisibleSaveComputerButton(Boolean b){
        this.saveButton.setVisible(b);
    }
    
    public void enableCombobox(boolean b) {
        this.computerTypeComboBox.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addComputerButton;
    private javax.swing.JTextField brandTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel computerBrandLabel;
    private javax.swing.JLabel computerEditorLabel;
    private javax.swing.JLabel computerModelLabel;
    private javax.swing.JLabel computerSerialLabel;
    private javax.swing.JTable computerTable;
    private javax.swing.JComboBox<String> computerTypeComboBox;
    private javax.swing.JLabel computerTypeLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField serialTextField;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JScrollPane userTableScrollPane;
    // End of variables declaration//GEN-END:variables

    

}
