/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import clock.IAlarmListener;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;


/**
 *
 * @author Lubián_Gañete_Julio_Miguel
 */

public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clock = new clock.ClockBean();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        manageDataMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        notificationMenu = new javax.swing.JMenu();
        notificationMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        manageDataMenuItem.setText("Manage data...");
        fileMenu.add(manageDataMenuItem);

        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        notificationMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Pictogrammers-Material-Bell.16.png"))); // NOI18N

        notificationMenuItem.setText("Notification");
        notificationMenu.add(notificationMenuItem);

        menuBar.add(notificationMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    public void setManageDataMenuItemListener(ActionListener listener) {
        this.manageDataMenuItem.addActionListener(listener);
    }
    
    public void addNotificationMenuItemListener(ActionListener listener) {
        this.notificationMenuItem.addActionListener(listener);
    }

    public void enableAlarm(boolean enable) {
        this.clock.setEnableAlarm(enable);
    }

    public void removeAlarm(IAlarmListener listener){
        this.clock.removeAlarmListener(listener);
    }
    
    public String getAlarmMessage() {
        return this.clock.getMessage();
    }

    public void setAlarmMessage(String message) {
        this.clock.setMessage(message);
    }

    public void setMode24(boolean mode24h) {
        this.clock.setMode24(mode24h);
    }

    public void setEnableAlarm(boolean enable) {
        this.clock.setEnableAlarm(enable);
    }

    public int getMinutesAlarm() {
        return this.clock.getMinutesAlarm();
    }

    public int getHourAlarm() {
        return this.clock.getHourAlarm();
    }

    public void setHourAlarm(int hour) {
        this.clock.setHourAlarm(hour);
    }

    public void setMinutesAlarm(int minute) {
        this.clock.setMinutesAlarm(minute);
    }

    public boolean isMode24() {
        return this.clock.isMode24();
    }

    public boolean isEnableAlarm() {
        return this.clock.isEnableAlarm();
    }

    public void addAlarmListener(IAlarmListener receptor) {
        this.clock.addAlarmListener(receptor);
    }

    public void setQuitMenuItemListener(ActionListener listener) {
        this.quitMenuItem.addActionListener(listener);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private clock.ClockBean clock;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem manageDataMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu notificationMenu;
    private javax.swing.JMenuItem notificationMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    // End of variables declaration//GEN-END:variables
}
