/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.donations;

import javax.swing.JOptionPane;

/**
 *
 * @author DAM2_Alu10
 */
public class donationsJDialog extends javax.swing.JDialog {

    /**
     * Creates new form donationsJDialog
     */
    public donationsJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phoneTypebuttonGroup = new javax.swing.ButtonGroup();
        promotionsbuttonGroup = new javax.swing.ButtonGroup();
        TitlejLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        mailjLabel = new javax.swing.JLabel();
        mailjTextField = new javax.swing.JTextField();
        phonejLabel = new javax.swing.JLabel();
        phonejTextField = new javax.swing.JTextField();
        phoneTypejLabel = new javax.swing.JLabel();
        housePhonejRadioButton = new javax.swing.JRadioButton();
        smartphonejRadioButton = new javax.swing.JRadioButton();
        personalDatajLabel = new javax.swing.JLabel();
        donationDatajLabel = new javax.swing.JLabel();
        donationDatejLabel = new javax.swing.JLabel();
        donationDatejTextField = new javax.swing.JTextField();
        materialTypejLabel = new javax.swing.JLabel();
        materialTypejComboBox = new javax.swing.JComboBox<>();
        numberOfItemsjLabel = new javax.swing.JLabel();
        numberOfItemsjSpinner = new javax.swing.JSpinner();
        promotionsjLabel = new javax.swing.JLabel();
        promotionsjCheckBox = new javax.swing.JCheckBox();
        submitjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TitlejLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        TitlejLabel.setText("Donaciones");

        namejLabel.setText("Nombre:");

        namejTextField.setToolTipText("Escriba aqui su nombre");

        mailjLabel.setText("Correo:");

        mailjTextField.setToolTipText("Escriba aqui su correo electronico");

        phonejLabel.setText("Telefono:");

        phonejTextField.setToolTipText("Escriba aqui su telefono");

        phoneTypejLabel.setText("Tipo de telefono:");

        phoneTypebuttonGroup.add(housePhonejRadioButton);
        housePhonejRadioButton.setText("Telefono Fijo");
        housePhonejRadioButton.setToolTipText("Indica que tu telefono es Fijo");

        phoneTypebuttonGroup.add(smartphonejRadioButton);
        smartphonejRadioButton.setText("Telefono Movil");
        smartphonejRadioButton.setToolTipText("Indica que tu telefono es Movil");

        personalDatajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        personalDatajLabel.setText("Datos Personales");

        donationDatajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        donationDatajLabel.setText("Datos Donacion");

        donationDatejLabel.setText("Fecha (DD/MM/YYY):");

        donationDatejTextField.setToolTipText("Escriba aqui la fecha de la donacion");

        materialTypejLabel.setText("Material:");

        materialTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Revista de Informatica", "Manual de Usuario", "Libro de Texto"}));
        materialTypejComboBox.setToolTipText("Seleccione el tipo de material a donar");

        numberOfItemsjLabel.setText("Nº de Ejemplares:");

        numberOfItemsjSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numberOfItemsjSpinner.setToolTipText("Seleccione aqui la cantidad del material");

        promotionsjLabel.setText("Desea recibir correos de promociones?");

        promotionsbuttonGroup.add(promotionsjCheckBox);
        promotionsjCheckBox.setText("Si");
        promotionsjCheckBox.setToolTipText("Click si quiere recibir correos de promociones");

        submitjButton.setText("Enviar Donacion");
        submitjButton.setToolTipText("Click para terminar la donacion y enviarla");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitlejLabel)
                .addGap(496, 496, 496))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personalDatajLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejLabel)
                            .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailjLabel)
                            .addComponent(mailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(phonejLabel)
                        .addComponent(phonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneTypejLabel)
                        .addComponent(housePhonejRadioButton)
                        .addComponent(smartphonejRadioButton)))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donationDatajLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(donationDatejLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(materialTypejComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                                .addComponent(donationDatejTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(materialTypejLabel))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfItemsjLabel)
                            .addComponent(numberOfItemsjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(promotionsjLabel))
                        .addGap(18, 18, 18)
                        .addComponent(promotionsjCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalDatajLabel)
                    .addComponent(donationDatajLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(donationDatejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donationDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mailjLabel)
                            .addComponent(materialTypejLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberOfItemsjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfItemsjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phonejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(promotionsjLabel)
                        .addComponent(promotionsjCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneTypejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housePhonejRadioButton)
                    .addComponent(submitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smartphonejRadioButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(this, "¿Está seguro de enviar la donacion?", "Confirmación", JOptionPane.YES_NO_OPTION);
        
        if (dialogResult == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Donación realizada");
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_submitjButtonActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JLabel donationDatajLabel;
    private javax.swing.JLabel donationDatejLabel;
    private javax.swing.JTextField donationDatejTextField;
    private javax.swing.JRadioButton housePhonejRadioButton;
    private javax.swing.JLabel mailjLabel;
    private javax.swing.JTextField mailjTextField;
    private javax.swing.JComboBox<String> materialTypejComboBox;
    private javax.swing.JLabel materialTypejLabel;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JLabel numberOfItemsjLabel;
    private javax.swing.JSpinner numberOfItemsjSpinner;
    private javax.swing.JLabel personalDatajLabel;
    private javax.swing.ButtonGroup phoneTypebuttonGroup;
    private javax.swing.JLabel phoneTypejLabel;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JTextField phonejTextField;
    private javax.swing.ButtonGroup promotionsbuttonGroup;
    private javax.swing.JCheckBox promotionsjCheckBox;
    private javax.swing.JLabel promotionsjLabel;
    private javax.swing.JRadioButton smartphonejRadioButton;
    private javax.swing.JButton submitjButton;
    // End of variables declaration//GEN-END:variables
}
